### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by ldionmarcil** [BuffaloWill/burpsuite-project-file-parser#3]
I've been trying to get this to work, but getting some errors, weird behaviours. I added the extension to a project and trying to operate the tool from the command line returns `Unrecognized command-line argument: --proxyHistory`:

```
$ /usr/local/Cellar/openjdk@11/11.0.10/bin/java -jar -Djava.awt.headless=true -Xmx2G ~/Downloads/burpsuite_pro_v2021.3.1.jar --project-file=/Users/louis.dionmarcil/myproject.burp --proxyHistory
Unrecognized command-line argument: --proxyHistory
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by burp.gsw (file:/Users/louis.dionmarcil/Downloads/burpsuite_pro_v2021.3.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of burp.gsw
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Deleting temporary files - please wait ... done.
```

I also tried with a user-setting file, as suggested, same behaviour as far as I can tell:

```
$ /usr/local/Cellar/openjdk@11/11.0.10/bin/java -jar -Djava.awt.headless=true -Xmx2G ~/Downloads/burpsuite_pro_v2021.3.1.jar --project-file=/Users/louis.dionmarcil/myproject.burp --user-config-file=/tmp/test.json --proxyHistory
Unrecognized command-line argument: --proxyHistory
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by burp.gsw (file:/Users/louis.dionmarcil/Downloads/burpsuite_pro_v2021.3.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of burp.gsw
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Deleting temporary files - please wait ... done.
```

The warnings 
```
WARNING: Illegal reflective access by burp.gsw (file:/Users/louis.dionmarcil/Downloads/burpsuite_pro_v2021.3.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
``` 

Occur with my JRE even without your extension, so I dont think it's related... Any help debugging this would be appreciated!

**Comment by ldionmarcil** [comment]
I managed to get it working by patching the code to ignore CLI arguments. Not sure if it's a new Burp thing, but the Burp launcher will return if it detects command line arguments it doesn't recognize, which includes those you've defined here. I suppose it could work with arguments that are not prefixed with dashes, like simply `java -jar ... printHistory`.

**Comment by BuffaloWill** [comment]
Thanks @ldionmarcil. 

Would you be interested in submitting a PR? Or I can update the README.md if it's something that the code can handle with slightly different flags.

**Comment by BuffaloWill** [comment]
Also, to answer your question this was my daily suite of tools last year, but I haven't been using it lately. I found it especially helpful to automate scanning tasks in a pipeline, build wordlists, and store data for later analysis. I haven't tested on the newest version of burp.

**Comment by ldionmarcil** [comment]
I'll submit one soon-ish!

**Comment by BuffaloWill** [comment]
@ldionmarcil I updated the code to support the newest version of Burp.

My theory is at some point the JRE or Burp Extender (not sure which) changed the order they loaded CLI arguments. Previously, extensions were loaded first so they could take on real CLI arguments (e.g. --auditItems). At some point this stopped being true so from the JRE or Burp's perspective `--auditItems` does not exist because the extension hasn't been loaded yet. 

To get around this I removed the "--" requirement on a flag for the extension (e.g. `--auditItems` becomes `auditItems`). Thank you for the suggestion in https://github.com/BuffaloWill/burpsuite-project-file-parser/issues/3#issuecomment-810523866. The following works for me in the newest version of Burp Suite Pro:

```
java -jar -Djava.awt.headless=true -Xmx2G --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED ~/Downloads/burpsuite_pro_v2022.3.6.jar --project-file="[MY PROJECT FILE].burp" auditItems

...

{"issueName":"External service interaction (DNS)","url":"https://somesite","confidence":"Certain","severity":"High"}
{"issueName":"External service interaction (DNS)","url":"https://somesite","confidence":"Certain","severity":"High"}
{"issueName":"External service interaction (HTTP)","url":"https://somesite","confidence":"Certain","severity":"High"}
```
